# Generated by Django 3.2.5 on 2021-10-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211012_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=225, verbose_name='Titulo de la receta')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion de la receta')),
                ('categoria', models.CharField(max_length=225, verbose_name='Categoria de la receta')),
                ('ingredientes', models.CharField(max_length=225, verbose_name='Ingredientes de la receta')),
                ('creador', models.EmailField(max_length=225, verbose_name='Creador de la receta')),
                ('opiniones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Opiniones')),
                ('calificacion', models.IntegerField(max_length=225, verbose_name='Nombre de la receta')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=225, verbose_name='Nombre del Usuario')),
                ('apellido', models.CharField(max_length=225, verbose_name='Apellido del Usuario')),
                ('apodo', models.CharField(max_length=225, verbose_name='Apodo del Usuario')),
                ('clave', models.CharField(max_length=30, verbose_name='Clave')),
                ('cedula', models.CharField(max_length=30, verbose_name='Cedula del Usuario')),
                ('fechaNacido', models.DateField(verbose_name='Fecha nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo del usuario:')),
                ('Facebook', models.URLField(blank=True, null=True, verbose_name='Facebook:')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Whatsapp:')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
