# Generated by Django 3.2.6 on 2021-11-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211115_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='clasificacion',
            field=models.CharField(choices=[('Lacteo', 'Lacteo'), ('Cereales', 'Cereales'), ('Dulces', 'Dulces'), ('Legumbres', 'Legumbres'), ('Fruta', 'Fruta'), ('Verdura', 'Verdura'), ('Carne', 'Carne'), ('Pescados', 'Pescados')], max_length=100, null=True, verbose_name='Clasificacion'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='idIngrediente',
            field=models.CharField(choices=[('2', '2')], max_length=100, verbose_name='Id del ingrendiente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.CharField(choices=[('3', '3')], max_length=100, verbose_name='Id del Usuario'),
        ),
    ]
