# Generated by Django 3.2.6 on 2021-11-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20211115_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='receta',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receta',
            name='calificacion',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Nombre de la receta'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='categoria',
            field=models.CharField(choices=[('marina', 'marina'), ('postres', 'postres')], max_length=225, verbose_name='Categoria de la receta'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='idReceta',
            field=models.CharField(choices=[('1', '1')], max_length=100, verbose_name='Id de la receta'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='opiniones',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Opiniones'),
        ),
    ]
