# Generated by Django 3.2.5 on 2021-11-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20211017_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('auto', models.CharField(max_length=100, verbose_name='Autor del comentario')),
                ('contenido', models.CharField(max_length=600, verbose_name='Comentario')),
                ('idDestino', models.CharField(max_length=225, verbose_name='Id receta')),
                ('fechaCreacion', models.DateTimeField(verbose_name='Fecha de creación')),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('idIngrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=225, verbose_name='Titulo del ingrediente')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion del ingrediente')),
                ('zonaOrigen', models.CharField(max_length=225, verbose_name='Luegar de origen')),
                ('clasificacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clasificacion')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='id',
            new_name='idReceta',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id',
            new_name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Facebook',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='receta',
            name='pub_date',
            field=models.DateTimeField(default=1, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receta',
            name='calificacion',
            field=models.IntegerField(verbose_name='Nombre de la receta'),
        ),
    ]
