# Generated by Django 3.2.6 on 2021-11-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20211115_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='calificacion2',
            field=models.IntegerField(default=1, max_length=100, verbose_name='Nombre de la receta'),
            preserve_default=False,
        ),
    ]
