# Generated by Django 3.2.6 on 2021-11-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_receta_calificacion2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='calificacion2',
        ),
    ]
