# Generated by Django 3.2.5 on 2021-11-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20211122_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='categoria',
            field=models.CharField(choices=[('marina', 'marina'), ('postres', 'postres'), ('tipico', 'tipico'), ('saludable', 'saludable'), ('sopas', 'sopas')], max_length=225, verbose_name='Categoria de la receta'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='pasosPre',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Como se prepara'),
        ),
    ]
