# Generated by Django 3.2.5 on 2021-11-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20211115_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='id',
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='idComentario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='idIngrediente',
            field=models.CharField(choices=[('1', '1')], max_length=100, verbose_name='Id del ingrendiente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.CharField(choices=[('1', '1')], max_length=100, verbose_name='Id del Usuario'),
        ),
    ]
