# Generated by Django 3.2.5 on 2021-11-14 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20211114_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='whatsap',
            new_name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='facebook',
        ),
    ]
