# Generated by Django 3.2.6 on 2021-11-15 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_receta_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='pub_date',
        ),
    ]
