# Generated by Django 3.2.5 on 2021-11-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20211115_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='idComentarioAux',
            field=models.CharField(default=None, max_length=100, verbose_name='Autor del comentario'),
            preserve_default=False,
        ),
    ]
