# Generated by Django 3.2.5 on 2021-11-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_ingrediente_idingrediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='idComentarioAux',
            field=models.CharField(choices=[('1', '1')], max_length=100, verbose_name='Autor del comentario'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='idReceta',
            field=models.CharField(choices=[('3', '3')], max_length=100, verbose_name='Id de la receta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.CharField(choices=[('2', '2')], max_length=100, verbose_name='Id del Usuario'),
        ),
    ]
