# Generated by Django 3.2.6 on 2021-11-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20211115_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='id',
        ),
        migrations.AddField(
            model_name='receta',
            name='bid',
            field=models.AutoField(db_column='BID', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receta',
            name='calificacion',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Nombre de la receta'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='categoria',
            field=models.CharField(choices=[('marina', 'marina'), ('postres', 'postres')], max_length=225, verbose_name='Categoria de la receta'),
        ),
    ]
