# Generated by Django 3.2.6 on 2021-11-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20211115_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idReceta', models.CharField(choices=[('1', '1')], max_length=100, verbose_name='Id de la receta')),
                ('titulo', models.CharField(max_length=225, verbose_name='Titulo de la receta')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion de la receta')),
                ('categoria', models.CharField(choices=[('marina', 'marina'), ('postres', 'postres')], max_length=225, verbose_name='Categoria de la receta')),
                ('ingredientes', models.CharField(max_length=225, verbose_name='Ingredientes de la receta')),
                ('creador', models.EmailField(max_length=225, verbose_name='Creador de la receta')),
                ('opiniones', models.CharField(blank=True, max_length=500, null=True, verbose_name='Opiniones')),
                ('calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Nombre de la receta')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
    ]
