# Generated by Django 3.2.6 on 2021-11-15 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20211115_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recetas',
            new_name='Receta',
        ),
    ]
